# Generated by Django 4.1.2 on 2022-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
